[package]
name = "opos-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.6.0"
toml = "0.8.19"
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-serial = "5.4.4"
async-std = "1.13.0"